spring:
  application:
    name:
  datasource:
    url: jdbc:mariadb://localhost:4001/anyclick_nac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  artemis:
    user: artemis
    password: artemis
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true
