spring:
  datasource:
    url: jdbc:mariadb://localhost:4001/anyclick_nac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin

    hikari:
      maximum-pool-size: 20
  sql:
    init:
      mode: always
      schema-locations: schema.sql

  artemis:
    user: artemis
    password: artemis
    broker-url: tcp://localhost:61616

  jms:
    pub-sub-domain: true

  task:
    execution:
      pool:
        core-size: 10
      thread-name-prefix: TASK-

logging:
  level:
    org:
      mq: info

env:
  publisher:
    interval-millis: 10000

  message-topic-name: logTopic


db-sync:
  jobs:
    - table_name: authlog
      thread_size: 1
      topic_name: sampleTopic
      interval_millis: 500
#      time_field_name:
#
#    - table_name: testtbl
#      thread_size: 1
#      topic_name: topic-${db-sync.jobs[0].table-name}
#      interval_millis: 500
#
#    - table_name: authlog
#      thread_size: 1
#      topic_name: topic-${db-sync.jobs[0].table-name}
#      interval_millis: 500
#
