#spring:
#  profiles:
#    active: @spring.profiles.active@
#

spring:
  application:
    name: DataBase Sync Application
  profiles:
    default: dev

--- # Dev application.yaml ------------------------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:~/dbSyncApplication
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  artemis:
    user: artemis
    password: artemis
    broker-url: tcp://localhost:61616

  jms:
    pub-sub-domain: true

logging:
  level:
    org.springframework.jms.listener: debug
    org.springframework.beans: debug

app:
  config:
    activemq:
      mode: default
      user: artemis
      password: artemis
      broker-url: tcp://localhost:61616

  db-sync:
    job:
      - table_name: authlog
        thread_size: 10
        topic_name: test1
        interval_millis: 10000
      #      time_field_name: //
      #      테이블마다 time_stamp 역할을 수행하는 테이블명이 다르다.
      #
      - table_name: testtbl
        thread_size: 10
        topic_name: test2
        interval_millis: 10000

--- # Test application.yaml ------------------------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/dbSyncApplication
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  artemis:
    user: artemis
    password: artemis
    broker-url: tcp://localhost:61616

  jms:
    pub-sub-domain: true

config:
  activemq:
    policy: basic
    user: artemis
    password: artemis
    broker-url: tcp://localhost:61616

  consumer:
    validate:
      sample:
        - destination: valid_destination1
        - destination: valid_destination2

    basic:
      test: test

#  db-sync:
#    job:
#      - table_name: authlog
#        thread_size: 10
#        topic_name: test1
#        interval_millis: 10000
#      #      time_field_name: //
#      #      테이블마다 time_stamp 역할을 수행하는 테이블명이 다르다.
#      #
#      - table_name: testtbl
#        thread_size: 10
#        topic_name: test2
#        interval_millis: 10000

--- # Prod application.yaml ------------------------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://localhost:4001/anyclick_nac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
