spring:

  datasource:
    url: jdbc:mariadb://localhost:4001/anyclick_nac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
#
#  artemis:
#    user: artemis
#    password: artemis
#    broker-url: tcp://localhost:61616

  jms:
    pub-sub-domain: true
  task:
    execution:
      pool:
        core-size: 10
      thread-name-prefix: TASK-

logging:
  level:
    org:
      mq: info

db-sync:
  jobs:
    - table_name: authlog
      thread_size: 10
      topic_name: sampleTopic
      interval_millis: 2000
#      time_field_name: //
#      테이블마다 time_stamp 역할을 수행하는 테이블명이 다르다.
#
    - table_name: testtbl
      thread_size: 10
      topic_name: topic-${db- sync.jobs[0].table-name}
      interval_millis: 2000
#
#    - table_name: authlog
#      thread_size: 1
#      topic_name: topic-${db-sync.jobs[0].table-name}
#      interval_millis: 500
#