spring:
  application:
    name: DataBase Sync Application
  profiles:
    default: prod

--- # Prod application.yaml ------------------------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://localhost:4001/anyclick_nac
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin

app:
  config:
    activemq:
      user: artemis
      password: artemis
      broker-url: tcp://localhost:61616

      publisher:
        timeslice:
          sync_info:
            - source_table: auth_log_tbl
              topic: auth_topic
              thread_size: 7
              interval_millis: 2000
            - source_table: system_log_tbl
              topic: system_topic
              thread_size: 3
              interval_millis: 1000

      consumer:
        basic:
          sync_info:
            - destination_table: sync_auth_log_tbl
              topic: auth_topic

            - destination_table: sync_system_log_tbl
              topic: system_topic
logging:
  level:
    org.broker: info

mybatis:
  mapper-locations: mapper/*.xml