name: Build Spring Boot Project
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -P test --file pom.xml

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v1.0.3
      with:
        ssh_key: ${{ secrets.AWS_PRIVATE_KEY}}
        host: ${{ secrets.AWS_HOST }}
        user: ${{ secrets.AWS_USER_NAME }}
        port: ${{ secrets.AWS_PORT }}
        target_directory: ~/test_app
        source_directory: target/MQ-0.0.1-SNAPSHOT.jar



